import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { useTranslation, Trans } from "react-i18next";
import LanguageSelector from "../components/language-selector";

export default function Home() {
    const router = useRouter();
    const { t } = useTranslation();
    const framework = "Next.js";
    const vercel = "vercel";

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main className={styles.main}>
                <form className={styles.description}>
                    <LanguageSelector />
                    <br />
                    <Link href={`/${router.query.locale ? router.query.locale : "en"}/contact`}>
                        <button>Go to Contact Us</button>
                    </Link>
                </form>
                <h1 className={styles.title}>
                    <Trans components={{ a: <a /> }}>index.welcome</Trans>
                </h1>

                <p className={styles.description}>
                    <Trans components={{ code: <code className={styles.code} /> }}>index.getting-started</Trans>
                </p>

                <div className={styles.grid}>
                    <a href="https://nextjs.org/docs" className={styles.card}>
                        <h2>
                            <Trans components={{ span: <span /> }}>index.documentation-title</Trans>
                            &rarr;
                        </h2>
                        <p>{t("index.documentation-text", { framework })}</p>
                    </a>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>
                            <Trans components={{ span: <span /> }}>index.learn-title</Trans>
                            &rarr;
                        </h2>
                        <p>{t("index.learn-text", { framework })}</p>
                    </a>

                    <a href="https://github.com/vercel/next.js/tree/master/examples" className={styles.card}>
                        <h2>
                            <Trans components={{ span: <span /> }}>index.examples-title</Trans>
                            &rarr;
                        </h2>
                        <p>{t("index.examples-text", { framework })}</p>
                    </a>

                    <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={styles.card}>
                        <h2>
                            <Trans components={{ span: <span /> }}>index.deploy-title</Trans>
                            &rarr;
                        </h2>
                        <p>{t("index.deploy-text", { framework, vercel })}</p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
                    {t("index.powered-by", { vercel })}
                </a>
            </footer>
        </div>
    );
}
